FROM perlt/workspace

ENV SHELL /bin/bash

RUN sudo apk add python3
RUN sudo apk add py3-pip

RUN sudo apk add terminus-font ttf-inconsolata ttf-dejavu font-noto font-noto-cjk ttf-font-awesome font-noto-extra
